authenticationCachePolicy: "maximumSize=10000, expireAfterAccess=10m"
database1:
  driverClass: org.h2.Driver
  url: jdbc:h2:./target/rufusdb
logging:
  appenders:
    -
      target: stdout
      threshold: ALL
      timeZone: UTC
      type: console
  level: INFO
database2:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  # database is stored in file at path below
  url: jdbc:hsqldb:file:target/rufushsqldb
  validationQuery: "SET DATABASE SQL SYNTAX MYS TRUE; SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"
logging:
  appenders:
    -
      target: stdout
      threshold: ALL
      timeZone: UTC
      type: console
  level: INFO
